version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
    app:
      container_name: snippets-app
      image: php:laravel
      volumes:
          - ./:/var/www/
          - ./public/:/var/www/html/
      labels:
        - traefik.frontend.rule=Host:snippets.samyerkes.com
        - traefik.docker.network=web
        - traefik.port=80
      networks:
        - web
        - internal
    db:
      container_name: snippets-db
      image: mysql:5.7
      volumes:
        - ./db-data:/var/lib/mysql
      env_file:
        - docker.env
      networks:
        - internal
      labels:
        - traefik.enable=false
